### ISSUE TITLE
Unable to load fonts (returning 404)

### ISSUE THREAD

**Issue by njj** [storybooks/storybook#1900]
Hi all, I've tried various approaches to getting my fonts to load, all which have failed.

The main application is routed through nginx, so I use the paths related to that i.e. `web-2` in the less files for loading the fonts:

I am using the `-s` flag when running storybook to point at `./assets/`

When loading the fonts, the less file looks something like:

```css
@font-face{
font-family:"Avenir-Roman";
src:url("/web-2/assets/fonts/avenir/57bf7902-79ee-4b31-a327-1bbf59a3d155.eot?#iefix");
src:url("/web-2/assets/fonts/avenir/57bf7902-79ee-4b31-a327-1bbf59a3d155.eot?#iefix") format("eot"),url("/web-2/assets/fonts/avenir/b290e775-e0f9-4980-914b-a4c32a5e3e36.woff2") format("woff2"),url("/web-2/assets/fonts/avenir/4b978f72-bb48-46c3-909a-2a8cd2f8819c.woff") format("woff"),url("/web-2/assets/fonts/avenir/9bdf0737-f98c-477a-9365-ffc41b9d1285.ttf") format("truetype"),url("/web-2/assets/fonts/avenir/15281d0d-e3c2-46e1-94db-cb681e00bfaa.svg#15281d0d-e3c2-46e1-94db-cb681e00bfaa") format("svg");
}
```

The console error I get is something similar to:

```log
 http://localhost:6006/web-2/assets/fonts/avenir/d513e15e-8f35-4129-ad05-481815e52625.woff2
```

Does anyone have any advice on how to get these to load properly?
