### ISSUE TITLE
Font-face not loading properly

### ISSUE THREAD

**Issue by renanvalentin** [storybooks/storybook#324]
Hey guys nice work!!!

I've could setup and running storybook, but I wasn't able to load static files:

this is my config:

**package.json:**
`"storybook": "start-storybook -p 9001"`

**webpack.config:**

``` javascript
const path = require('path');

const localIdentName = '[name]__[local]___[hash:base64:5]';

const cssLoader = [
  'css?minimize&modules',
  'sourceMap',
  'importLoaders=1',
  'localIdentName=' + localIdentName
].join('&');

const fontsFileName = `fonts/[name].[ext]`;
const imagesFileName = `img/[name].[ext]`;

module.exports = {
  resolve: {
    root: path.resolve(__dirname, '../src'),
    extensions: ['', '.js', '.jsx']
  },
  module: {
    loaders: [
      {
        test: /\.scss$/,
        include: path.resolve(__dirname, '../src'),
        loaders: [
          'style',
          cssLoader,
          'postcss-loader',
          'sass?sourceMap'
        ]
      },
      {
        test: /\.woff(\?.*)?$/,
        loader: `url?prefix=fonts/&name=${fontsFileName}&limit=10000&mimetype=application/font-woff`,
      },
      {
        test: /\.woff2(\?.*)?$/,
        loader: `url?prefix=fonts/&name=${fontsFileName}&limit=10000&mimetype=application/font-woff2`
      },
      {
        test: /\.ttf(\?.*)?$/,
        loader: `url?prefix=fonts/&name=${fontsFileName}&limit=10000&mimetype=application/octet-stream`
      },
      {test: /\.eot(\?.*)?$/, loader: `file?prefix=fonts/&name=${fontsFileName}`},
      {test: /\.svg(\?.*)?$/, loader: `url?prefix=fonts/&name=${fontsFileName}&limit=10000&mimetype=image/svg+xml`},
      {test: /\.(png|jpg)$/, loader: `url?limit=5192&name=${imagesFileName}`}
    ]
  },
  sassLoader: {
    includePaths: path.resolve(__dirname, '../src/styles')
  }
};
```

this is the output created by webpack:

``` css
@font-face{
   font-family:lato;src:url(/static/fonts/Lato-Regular.ttf);
   font-weight:400;
   font-style:normal
}

@font-face{
   font-family:lato;src:url(/static/fonts/Lato-Semibold.ttf);
   font-weight:600;
   font-style:normal
}

@font-face{
   font-family:lato;
   src:url(/static/fonts/Lato-Light.ttf);
   font-weight:300;
   font-style:normal
}
```

If I hit **localhost:9001/static/fonts/Lato-Regular.ttf** it will download the font properly, but when I load the page it is not loaded :/

![screen shot 2016-07-19 at 1 09 00 pm](https://cloud.githubusercontent.com/assets/2846918/16959305/743a7396-4db2-11e6-978f-d7ea448cc558.png)

Any ideas?

Thanks in advance!

**Comment by mnmtanish** [comment]
Hi @renanvalentin 
Add the `-s` switch with `start-storybook` command as explained [here](https://github.com/kadirahq/react-storybook/blob/master/docs/configure_storybook.md#static-directory).

```
start-storybook -p 6977 -s ./public
```

**Comment by renanvalentin** [comment]
Hi @mnmtanish !

I've tried that before, my fonts are located at:

```
.
|--src
|----fonts
```

and my package is like this:

`"storybook": "start-storybook -p 9001 -s ./src/fonts"`

I've should be doing something wrong, because I can request it from the browser :/

**Comment by renanvalentin** [comment]
I couldn't figure out why it is not working, but after increasing the url limit loader size from 10000 to 100000 it started to work. that's crazy 🚶 .

**Comment by renanvalentin** [comment]
It's using base64 now, I suppose that was some encoding problem. 😞

**Comment by edorivai** [comment]
Having the exact same problem.

Webpack/storybook generates the following CSS:

```css
@font-face {
  font-family: 'Montserrat';
  src: url(/static/0ae39139cfa9ae65e514ebb0a04452d8.woff2) format("woff2"), url(/static/82797e193fe5263e88f901eaaac800d8.woff) format("woff");
}
```

But none of the woff files is ever loaded:
![screenshot from 2016-08-01 15-37-32](https://cloud.githubusercontent.com/assets/765358/17295744/f6c1e10a-57fd-11e6-8386-932ce35d309e.png)

I've added the `-s` flag: `start-storybook -p 9001 -c ./src/.storybook -s ./static/dist`, which works perfectly fine with images.

The relevant font loaders:

```js
{ test: /\.woff(\?v=\d+\.\d+\.\d+)?$/, loader: 'url?limit=10000&mimetype=application/font-woff' },
{ test: /\.woff2(\?v=\d+\.\d+\.\d+)?$/, loader: 'url?limit=10000&mimetype=application/font-woff' },
```

And like @renanvalentin, the font works in inline/base64 mode (when I increase the file limit).

Additionally, my production build and webpack-dev-server work fine. The woff files are properly loaded if I spin up my complete app.
