### ISSUE TITLE
How to add global styles without impacting the content generated by the info addon?

### ISSUE THREAD

**Issue by mlegait** [storybooks/storybook#3881]
### Bug or support request summary

I would like the components to have the same look and feel in storybook and in the application where they are used. That's why I would like to apply in storybook the same `reset.css` and the same global styles (`font-family`, `color`, `box-sizing`, ...) as in the application. 
My concern is that theses global styles are also applied to the content generated by the **info addon**. And the `reset.css` completely breaks the markdown 😕 

So here is my question: **How can I apply global styles to my components without impacting the content generated by the info addon?**

### Steps to reproduce

```js
// config.js
require('../src/reset.scss'); // from Eric Meyer
require('./storybook.scss');
```
```scss
// storybook.scss
@import 'variables';
html {
  background-color: $color-white-smoke;
  color: $color-dark-lava;
  font-family: Helvetica, sans-serif;
  font-size: 14px;
}

*,
*::before,
*::after {
  box-sizing: border-box;
}
```

I use markdown to describe the component with the addon info, but the style is completely broken by `reset.css`. We don't see anymore bullet lists, strong text, ...

Instead of using the `html` selector I could use `#root` but the content generated by info is also in this div and I have no other id or class to help me target only my components. 

Maybe **a solution could be to add an id on the div that encapsulates the component and nothing else**. What do you think?

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react@3.4.8
- @storybook/addon-info@3.4.8
